package eleeter.unifystudiox.input;

public enum Action
{

    CAMERA_MOVE_FORWARD,
    CAMERA_MOVE_BACKWARD,
    CAMERA_STRAFE_LEFT,
    CAMERA_STRAFE_RIGHT,
    CAMERA_MOVE_UP,
    CAMERA_MOVE_DOWN,
    CAMERA_LOOK_LEFT,
    CAMERA_LOOK_RIGHT,

    TOGGLE_PLAY,
    UNDO,
    REDO,
    SELECT,
    DESELECT_ALL,
    DELETE_SELECTED,

    GIZMO_TRANSLATE,
    GIZMO_ROTATE,
    GIZMO_SCALE,

    TOGGLE_FULLSCREEN,
    TOGGLE_WIREFRAME,
    SCREENSHOT;
}
